# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class JobdaadItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    code = scrapy.Field()
    created  = scrapy.Field()
    contactadresszusatz  = scrapy.Field()
    contactasprache  = scrapy.Field()
    contactasprache_key  = scrapy.Field()
    contactasprache_value  = scrapy.Field()
    contactdsprache  = scrapy.Field()
    contactdsprache_key = scrapy.Field()
    contactdsprache_value = scrapy.Field()
    contactemail = scrapy.Field()
    contactfax = scrapy.Field()
    contactfirstname = scrapy.Field()
    contactinstitution = scrapy.Field()
    contactlastname = scrapy.Field()
    contactlogo = scrapy.Field()
    contactorganisation = scrapy.Field()
    contactort = scrapy.Field()
    contactplz = scrapy.Field()
    contactposition = scrapy.Field()
    contactstrasse = scrapy.Field()
    contacttelefon = scrapy.Field()
    contacttitel = scrapy.Field()
    contactunterlagen = scrapy.Field()
    contactunterlagen_key = scrapy.Field()
    contactunterlagen_value = scrapy.Field()
    contactunterlagenotherde = scrapy.Field()
    contactunterlagenotheren = scrapy.Field()
    contacturl = scrapy.Field()
    contactvoraussetzungde = scrapy.Field()
    contactvoraussetzungen = scrapy.Field()
    created = scrapy.Field()
    created_key = scrapy.Field()
    offerangebotsurl = scrapy.Field()
    offeranzahl = scrapy.Field()
    offerbeginn = scrapy.Field()
    offerbeginn_key = scrapy.Field()
    offerbeginn_value = scrapy.Field()
    offerbeschreibungde = scrapy.Field()
    offerbeschreibungen = scrapy.Field()
    offerdauer = scrapy.Field()
    offerdauerde = scrapy.Field()
    offerdaueren = scrapy.Field()
    offerdeadline = scrapy.Field()
    offerdeadline_key = scrapy.Field()
    offerdeadline_value = scrapy.Field()
    offerfachgebietde = scrapy.Field()
    offerfachgebieten = scrapy.Field()
    offerfachrichtung = scrapy.Field()
    offerfachrichtung_key = scrapy.Field()
    offerfachrichtung_value = scrapy.Field()
    offerfinanzierung = scrapy.Field()
    offerfinanzierung_key = scrapy.Field()
    offerfinanzierung_value = scrapy.Field()
    offerpromotion = scrapy.Field()
    offerpromotion_key = scrapy.Field()
    offerpromotion_value = scrapy.Field()
    offertitelde = scrapy.Field()
    offertitelen = scrapy.Field()
    updated = scrapy.Field()
    updated_key = scrapy.Field()